# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Audubon'
    subscriptionId: '85a8e4f0-014f-45c8-bec2-60863699a706'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Fast_Lane'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jmaamj/ARM/main/azuredeploy.json'
    overrideParameters: '-projectName jma6789'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'



- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Candy'
    publishLocation: 'pipeline'


- task: ArchiveFiles@2
  displayName: 'Cocoa Puff'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/_jmaamj.ARM/Candy/s'
    includeRootFolder: false

