# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dimminz'
    subscriptionId: '590eb0b1-e900-44ae-96cc-b4154b5410e4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Paine'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jmaamj/ARM/main/azuredeploy.json'
    overrideParameters: '-projectName jma6789'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/_jmaamj.ARM/Candy/s'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Candy'
    publishLocation: 'pipeline'
